### ISSUE TITLE
Thoughts about using a frontend framework  ?

### ISSUE THREAD

**Issue by kiloreux** [AgileVentures/WebsitePotential-archive#1]
Do you think we should use one of the frontend frameworks (ember maybe) in the new website ?

**Comment by yggie** [comment]
good question, I believe this is open to discussion, we could leave this to a vote. Though I think we should focus on the required features first before we decide on the tech stack to use.

**Comment by Kiloreux** [comment]
@yggie  yeah it was just a random thought, have you started specifying  requirements for the project, would love to participate if possible, thanks.

**Comment by yggie** [comment]
@Kiloreux any help would be welcome :grinning:

**Comment by tansaku** [comment]
@Kiloreux yeah I'd be excited to use something new :-)

**Comment by joaopapereira** [comment]
Just some food for though:
https://www.airpair.com/js/javascript-framework-comparison

**Comment by Kiloreux** [comment]
@tansaku @yggie  maybe we should plan a G+ Hangout and further discuss it .

**Comment by razorcd** [comment]
+1 for angular
+1 for angular with ES6

**Comment by yggie** [comment]
@Kiloreux :+1: I am up for hangouts

**Comment by tansaku** [comment]
@Kiloreux feel free to join any scrum/standup hangout on the usual schedule to get started with discussing http://www.agileventures.org/about-us
